### ISSUE TITLE
Image buffer is not large enough

### ISSUE THREAD

**Issue by raffaelemancuso** [OtaK/hide-my-mess-rs#5]
When I try to run this with my laptop webcam, I get this error which asks to be reported:

```
❯  INFO  hide_my_mess > Selected camera: #0 - [MY_WEBCAM_MODEL]
 INFO  hide_my_mess > Camera Format selected: 800x600@30fps
 INFO  hide_my_mess > Active Camera Format: 800x600@30fps
 INFO  hide_my_mess > Fake Camera found at index #4
 INFO  hide_my_mess > Loading ML Inference model...
Error: Webcam(ReadFrameError("ImageBuffer is not large enough! This is probably a bug, please report it!"))
```

**Comment by OtaK** [comment]
Thanks!

I traced it to an old version of nokwha (the webcam capture library I'm using): https://docs.rs/nokhwa/0.9.4/src/nokhwa/backends/capture/avfoundation.rs.html#264

This should be fixed once I update everything to its latest version :)
